name: CodeCov
on: [push]
# on: 
#   # Replace with your main branch if needed
#   push:
#     branches:
#       - master
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.11'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.10
    - name: 'generate report'
      run: |
        pip install pytest
        pip install coverage
        pip install -r requirements.txt
        coverage run --omit="*/examples/*" -m pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
